/**
 * Saskatchewan Seed Data
 */

module.exports = {
    province: { id: 'ca-sk', name: 'Saskatchewan', code: 'SK' },
    
    federalRidings: [
        "Blackstrap", "Cypress Hills / Grasslands", "Desnethe / Missinippi / Churchill River",
        "Palliser", "Prince Albert", "Regina / Lumsden / Lake Centre", "Regina / QuAppelle",
        "Saskatoon / Humboldt", "Saskatoon / Rosetown / Biggar", "Saskatoon / Wanuskewin",
        "Souris / Moose Mountain", "Wascana", "Yorkton / Melville"
    ],
    
    provincialRidings: [
        "Regina University", "Regina Lakeview", "Athabasca", "Moosomin", "Carrot River Valley",
        "Arm River", "Saskatoon Westview", "Estevan", "Saskatoon Riversdale",
        "Saskatoon Willowgrove", "The Battlefords", "Cannington", "Canora-Pelly",
        "Regina Coronation Park", "Cut Knife-Turtleford", "Weyburn-Big Muddy",
        "Saskatoon Stonebridge-Dakota", "Regina Pasqua", "Saskatoon Centre", "Kindersley",
        "Melfort", "Prince Albert Carlton", "Humboldt-Watrous", "Meadow Lake",
        "Last Mountain-Touchwood", "Martensville-Warman", "Swift Current", "Melville-Saltcoats",
        "Batoche", "Saskatoon Churchill-Wildwood", "Moose Jaw-Wakamow", "Regina Gardiner Park",
        "Wood River", "Regina Elphinstone-Centre", "Indian Head-Milestone", "Saskatoon Meewasin",
        "Saskatoon Silverspring-Sutherland", "Moose Jaw North", "Rosthern-Shellbrook",
        "Saskatoon Southeast", "Saskatoon Fairview", "Kelvington-Wadena", "Saskatoon University",
        "Yorkton", "Regina Northeast", "Prince Albert Northcote", "Rosetown-Elrose",
        "Regina Rochdale", "Regina Douglas Park", "Saskatoon Nutana", "Cypress Hills",
        "Lumsden-Morse", "Regina Wascana Plains", "Cumberland", "Biggar-Sask Valley",
        "Saskatchewan Rivers", "Regina Rosemont", "Saskatoon Northwest", "Lloydminster",
        "Saskatoon Eastview", "Regina Walsh Acres"
    ],
    
    towns: [
        "Abbey", "Aberdeen", "Abernethy", "Alameda", "Albertville", "Alice Beach", "Alida",
        "Allan", "Alvena", "Annaheim", "Aquadeo", "Arborfield", "Archerwill", "Arcola",
        "Arran", "Asquith", "Assiniboia", "Atwater", "Avonlea", "Aylesbury", "Aylsham",
        "B-Say-Tah", "Balcarres", "Balgonie", "Bangor", "Battleford", "Beatty", "Beaver Flat",
        "Beechy", "Belle Plaine", "Bengough", "Bethune", "Bienfait", "Big River", "Big Shell",
        "Biggar", "Birch Hills", "Bird's Point", "Bjorkdale", "Bladworth", "Blaine Lake",
        "Borden", "Bracken", "Briercrest", "Broadview", "Broc", "Broderick", "Brownlee",
        "Bruno", "Buchanan", "Buena Vista", "Bulyea", "Burstall", "Cabri", "Cadillac",
        "Calder", "Candle Lake", "Canora", "Canwood", "Carievale", "Carlyle", "Carnduff",
        "Caronport", "Carrot River", "Central Butte", "Ceylon", "Chamberlain", "Chaplin",
        "Chitek Lake", "Choiceland", "Chorney Beach", "Christopher Lake", "Churchbridge",
        "Clavet", "Climax", "Cochin", "Coderre", "Codette", "Coleville", "Colonsay",
        "Conquest", "Consul", "Coronach", "Coteau Beach", "Craik", "Craven", "Creelman",
        "Cudworth", "Cupar", "Cut Knife", "Dafoe", "Dalmeny", "Davidson", "Debden",
        "Delisle", "Denholm", "Denzil", "Dilke", "Dinsmore", "Disley", "Dodsland",
        "Dorintosh", "Drake", "Drinkwater", "Dubuc", "Duck Lake", "Duff", "Dundurn",
        "Duval", "Dysart", "Earl Grey", "Eastend", "Eatonia", "Ebenezer", "Echo Bay",
        "Edam", "Edenwold", "Elbow", "Elfros", "Elrose", "Endeavour", "Englefeld",
        "Ernfold", "Esterhazy", "Estevan", "Eston", "Etters Beach", "Eyebrow", "Fairlight",
        "Fenwood", "Fillmore", "Findlater", "Flaxcombe", "Fleming", "Flin Flon",
        "Foam Lake", "Forget", "Fort Qu'Appelle", "Fort San", "Fosston", "Fox Valley",
        "Francis", "Frobisher", "Frontier", "Gainsborough", "Gerald", "Glaslyn",
        "Glen Ewen", "Glen Harbour", "Glenavon", "Glenside", "Golden Prairie", "Goodeve",
        "Goodsoil", "Goodwater", "Govan", "Grand Coulee", "Grandview Beach", "Gravelbourg",
        "Grayson", "Greig Lake", "Grenfell", "Gull Lake", "Hafford", "Hague", "Halbrite",
        "Hanley", "Harris", "Hawarden", "Hazenmore", "Hazlet", "Hepburn", "Herbert",
        "Heward", "Hodgeville", "Holdfast", "Hubbard", "Hudson Bay", "Humboldt", "Hyas",
        "Imperial", "Indian Head", "Invermay", "Island View", "Ituna", "Jansen", "Kamsack",
        "Kannata Valley", "Katepwa", "Keeler", "Kelliher", "Kelvington", "Kenaston",
        "Kendal", "Kennedy", "Kenosee Lake", "Kerrobert", "Killaly", "Kincaid", "Kindersley",
        "Kinistino", "Kinley", "Kipling", "Kisbey", "Kivimaa-Moonlight Bay", "Krydor",
        "Kyle", "Lafleche", "Laird", "Lake Lenore", "Lampman", "Lancer", "Landis", "Lang",
        "Langenburg", "Langham", "Lanigan", "Lashburn", "Leader", "Leask", "Lebret",
        "Lemberg", "Leoville", "Leross", "Leroy", "Leslie Beach", "Liberty", "Limerick",
        "Lintlaw", "Lipton", "Lloydminster", "Loon Lake", "Loreburn", "Love", "Lucky Lake",
        "Lumsden", "Lumsden Beach", "Luseland", "Macklin", "MacNutt", "Macoun", "Macrorie",
        "Maidstone", "Major", "Makwa", "Manitou Beach", "Mankota", "Manor", "Maple Creek",
        "Marcelin", "Marengo", "Margo", "Markinch", "Marquis", "Marsden", "Marshall",
        "Martensville", "Maryfield", "Maymont", "McLean", "McTaggart", "Meacham",
        "Meadow Lake", "Meath Park", "Medstead", "Melfort", "Melville", "Melville Beach",
        "Mendham", "Meota", "Mervin", "Metinota", "Midale", "Middle Lake", "Milden",
        "Milestone", "Minton", "Mistatim", "Mistusinne", "Montmartre", "Moose Jaw",
        "Moosomin", "Morse", "Mortlach", "Mossbank", "Muenster", "Naicam", "Neilburg",
        "Netherhill", "Neudorf", "Neville", "Nipawin", "Nokomis", "Norquay",
        "North Battleford", "North Grove", "North Portal", "Odessa", "Ogema", "Osage",
        "Osler", "Outlook", "Oxbow", "Paddockwood", "Pangman", "Paradise Hill", "Parkside",
        "Paynton", "Pebble Baye", "Pelican Pointe", "Pelly", "Pennant", "Pense", "Perdue",
        "Pierceland", "Pilger", "Pilot Butte", "Pleasantdale", "Plenty", "Plunkett",
        "Ponteix", "Porcupine Plain", "Preeceville", "Prelate", "Prince Albert",
        "Prud'homme", "Punnichy", "Qu'Appelle", "Quill Lake", "Quinton", "Radisson",
        "Radville", "Rama", "Raymore", "Redvers", "Regina", "Regina Beach", "Rhein",
        "Richard", "Richmound", "Ridgedale", "Riverhurst", "Rocanville", "Roche Percee",
        "Rockglen", "Rose Valley", "Rosetown", "Rosthern", "Rouleau", "Ruddell",
        "Rush Lake", "Saltcoats", "Saskatchewan Beach", "Saskatoon", "Sceptre", "Scott",
        "Sedley", "Semans", "Senlac", "Shamrock", "Shaunavon", "Sheho", "Shell Lake",
        "Shellbrook", "Shields", "Silton", "Simpson", "Sintaluta", "Smeaton", "Smiley",
        "South Lake", "Southey", "Spalding", "Speers", "Spiritwood", "Springside",
        "Spy Hill", "St. Benedict", "St. Brieux", "St. Gregor", "St. Louis", "St. Walburg",
        "Star City", "Stenen", "Stewart Valley", "Stockholm", "Storthoaks", "Stoughton",
        "Strasbourg", "Strongfield", "Sturgis", "Success", "Sun Valley", "Sunset Cove",
        "Swift Current", "Tantallon", "Tessier", "Theodore", "Thode", "Tisdale",
        "Tobin Lake", "Togo", "Tompkins", "Torquay", "Tramping Lake", "Tugaske",
        "Turtleford", "Tuxford", "Unity", "Val Marie", "Valparaiso", "Vanguard", "Vanscoy",
        "Vibank", "Viscount", "Vonda", "Wadena", "Wakaw", "Wakaw Lake", "Waldeck",
        "Waldheim", "Waldron", "Wapella", "Warman", "Waseca", "Watrous", "Watson",
        "Wawota", "Webb", "Wee Too Beach", "Weekes", "Weirdale", "Weldon", "West End",
        "Weyburn", "White City", "White Fox", "Whitewood", "Wilcox", "Wilkie",
        "Willow Bunch", "Windthorst", "Wiseton", "Wolseley", "Wood Mountain", "Wynyard",
        "Yarbo", "Yellow Grass", "Yorkton", "Young", "Zealandia", "Zelma", "Zenon Park"
    ],
    
    firstNations: [
        "Ahtahkakoop First Nation", "Amiskosakahikan First Nation",
        "Asimakaniseekan Askiy First Nation", "Assiniboine First Nation",
        "Beardy's & Okemasis First Nations", "Big Island Lake Cree Nation",
        "Big River First Nation", "Birch Narrows First Nation",
        "Black Lake Denesuline First Nation", "Buffalo River Dene Nation",
        "Canoe Lake First Nation", "Carry the Kettle Nakoda First Nation",
        "Clearwater River Dene Nation", "Coté First Nation",
        "Cumberland House First Nation", "Day Star First Nation",
        "Eagles Lake First Nation", "English River First Nation",
        "Fishing Lake Saulteaux Nation", "Flying Dust First Nation",
        "Fond du Lac Dene Nation", "George Gordon First Nation",
        "Hatchet Lake Dene Nation", "James Smith First Nation",
        "John Smith First Nation", "Joseph Bighead First Nation",
        "Kahkewistahaw First Nation", "Kawacatoose First Nation",
        "Keeseekoose First Nation", "The Key First Nation",
        "Kinistin First Nation", "Lac La Ronge First Nation",
        "Little Black Bear First Nation", "Little Pine First Nation",
        "Little Red River", "Lucky Man Cree Nation",
        "Makwa Sahgaiehcan First Nation", "Mistawasis First Nation",
        "Moosomin First Nation", "Montreal Lake First Nation",
        "Mosquito-Grizzly Bear's Head-Lean Man", "Muscowpetung First Nation",
        "Muskeg Lake Cree Nation", "Muskoday First Nation",
        "Muskowekwan First Nation", "Nekaneet Cree Nation",
        "Ocean Man First Nation", "Ochapowace Cree Nation",
        "Okanese First Nation", "One Arrow First Nation",
        "Onion Lake Cree Nation", "Pasqua First Nation",
        "Peepeekisis First Nation", "Pelican Lake",
        "Piapot Cree Nation", "Peter Ballantyne Cree Nation",
        "Pheasant Rump First Nation", "Pinehouse",
        "Poundmaker Cree Nation", "Red Earth First Nation",
        "Red Pheasant First Nation", "Sakimay First Nation",
        "Saulteaux First Nation", "Seekaskootch First Nation",
        "Shoal Lake Cree Nation", "Standing Buffalo First Nation",
        "Star Blanket Cree Nation", "Sturgeon Lake First Nation",
        "Sweetgrass First Nation", "Thunderchild First Nation",
        "Treaty Four Reserve Grounds", "Turnor Lake",
        "Wapachewunak", "Waterhen First Nation",
        "Weldon", "Weyakwin", "White Bear First Nation",
        "Whitecap Dakota First Nation", "Willow Cree Reserve",
        "Witchekan Lake First Nation", "Wood Mountain Sioux First Nation",
        "Yellow Quill First Nation"
    ]
};

